---
- name: java install
  become: yes
  hosts: all
  tasks:
    - name:  install java-11-openjdk-devel
      yum:
        name: java-11-openjdk-devel
        update_cache: yes
        state: presentgit status
        